"""notifier settings moved to separate table

Revision ID: 944a50460ef6
Revises: 70acc21ab47c
Create Date: 2026-03-13 19:19:50.634591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '944a50460ef6'
down_revision: Union[str, Sequence[str], None] = '70acc21ab47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_notifier_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enable_all_notifications', sa.Boolean(), nullable=False),
    sa.Column('mins_before_dt_start', sa.JSON(), nullable=False),
    sa.Column('progress_dt_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('today_dt_list_notification_time', sa.Time(), nullable=True),
    sa.Column('today_dt_completion_analyze_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'notify_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('users_notifier_settings')
    # ### end Alembic commands ###
