"""delay task minutes setting add

Revision ID: a29bc9c5f875
Revises: 944a50460ef6
Create Date: 2026-04-01 13:58:13.519284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29bc9c5f875'
down_revision: Union[str, Sequence[str], None] = '944a50460ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_notifier_settings', sa.Column('task_progress_delay_mins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE users_notifier_settings SET task_progress_delay_mins = 5;')
    op.alter_column('users_notifier_settings', 'task_progress_delay_mins', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_notifier_settings', 'task_progress_delay_mins')
    # ### end Alembic commands ###
